apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment
  namespace: capabilities-added
spec:
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
      annotations:
        container.apparmor.security.beta.kubernetes.io/container: runtime/default
    spec:
      containers:
        - name: container
          image: scratch
          securityContext:
            capabilities:
              drop:
                - AUDIT_WRITE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - NET_RAW
                - SETFCAP
                - SETPCAP
                - SYS_CHROOT
            allowPrivilegeEscalation: false
            privileged: false
          resources: {}
      automountServiceAccountToken: false
  strategy: {}
