package cmd

const (
	KubeAuditInfo = iota
	ErrorCapabilitiesAddedOrNotDropped
	ErrorCapabilitiesNIL
	ErrorImageTagIncorrect
	ErrorImageTagMissing
	ErrorReadOnlyRootFilesystemFalse
	ErrorReadOnlyRootFilesystemNIL
	ErrorRunAsNonRootFalse
	ErrorRunAsNonRootNIL
	ErrorSecurityContextNIL
	ErrorServiceAccountTokenDeprecated
	ErrorServiceAccountTokenNIL
	ErrorServiceAccountTokenNILAndNoName
	ErrorServiceAccountTokenNoName
	ErrorServiceAccountTokenTrueAndNoName
)
