package cmd

const (
	_ = iota
	KubeauditInternalError
	ErrorAllowPrivilegeEscalationNIL
	ErrorAllowPrivilegeEscalationTrue
	ErrorCapabilitiesAdded
	ErrorCapabilitiesNIL
	ErrorCapabilitiesNoneDropped
	ErrorCapabilitiesSomeDropped
	ErrorImageTagIncorrect
	ErrorImageTagMissing
	ErrorPrivilegedNIL
	ErrorPrivilegedTrue
	ErrorReadOnlyRootFilesystemFalse
	ErrorReadOnlyRootFilesystemNIL
	ErrorRunAsNonRootFalse
	ErrorRunAsNonRootNIL
	ErrorSecurityContextNIL
	ErrorServiceAccountTokenDeprecated
	ErrorServiceAccountTokenNIL
	ErrorServiceAccountTokenNILAndNoName
	ErrorServiceAccountTokenNoName
	ErrorServiceAccountTokenTrueAndNoName
	InfoImageCorrect
)
