name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.x"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install kubectl
        run: sudo snap install kubectl --classic
      - name: Install kind
        run: GO111MODULE=on go get sigs.k8s.io/kind
      - name: Go mod download and go tidy
        run: make setup
      - name: Run tests
        run: make test
