name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.1"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install kubectl
        run: sudo snap install kubectl --classic
      - name: Install kind
        run: go get sigs.k8s.io/kind
      - name: Go mod download and go tidy
        run: make setup
      - name: Run tests
        env:
          USE_KIND: "true"
        run: make test
